name: Node.js CI/CD for Vue

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build
        
    - name: List contents of dist folder
      run: ls ./dist

    - name: Deploy to Windows Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.WINDOWS_SERVER_IP }}
        username: ${{ secrets.WINDOWS_SERVER_USERNAME }}
        password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
        source: "./dist/*"  
        target: "C://root//web//dangerous//deploy"

    - name: Execute PowerShell Script
      run: |
        sshpass -p "${{ secrets.WINDOWS_SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.WINDOWS_SERVER_USERNAME }}@${{ secrets.WINDOWS_SERVER_IP }}" "powershell -File C://root/deploy/move_vue_strawberry.ps1"

